#! /bin/sh

PREREQ=""
DESCRIPTION="Disabling the lock screen for LXQt (LP: #2000787)..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

# Remove the Lock Screen menu entry
rm -f /root/usr/share/applications/lxqt-lockscreen.desktop

# Remove the autostart entry for xscreensaver
rm -f /root/etc/xdg/autostart/lxqt-xscreensaver-autostart.desktop

log_end_msg
